name: app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stated: 1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  flutter_launcher_icons: 0.10.0
  just_audio: 0.9.30

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/app-icon.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
